services:
  - type: web
    name: pastelaria-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: pastelaria-api
          property: port